<table border="0" cellpadding="0" cellspacing="0" width="100%">

    <tr>
    
    <td bgcolor="#E6E6CC" width="35%" height="40"><font face="Arial"> <strong><font color="#0000A0"><big>&nbsp; Programando em PHP</big></font><br>
    
    <font color="#0000FF"><small>&nbsp;&nbsp; Conceitos e
    
    Aplicações</small></font></strong></font></td>
    
    <td width="35%" bgcolor="#E6E6CC" height="40"><p align="center">
    
    <font face="Arial"><small><strong> <?php
    
    echo $capitulo;
    
    ?>
    
    </strong></small> </font></td>
    
    <td width="30%" bgcolor="#E6E6CC" height="40"><p align="right">
    
    <?php
    echo $data;
    ?>
    
    <font face="Arial" color="#0000FF"><small><strong>
    
    
    
    &nbsp;&nbsp; </strong></small></font></td>
</tr>

<tr>

<td width="35%" height="35"></td>

<td width="35%" height="35"></td>

<td width="30%" height="35"></td>

</tr>

<td width="100%" colspan="3"><p align="center"><font

face="Arial"><strong>

<?php
echo $descricao;
?>



</strong></font></td>

</tr>

<tr>

<td width="100%" colspan="3" height="25"><font face="Arial">

</font></td>

</tr>

</table>